[go]
name = "Go"
url = "go.dev"
date = 2025-03-29
syntax = true
noscroll = false
interactive = true

[toml]
name = "TOML"
url = "toml.io"
date = 2025-03-29
syntax = true
noscroll = true
interactive = false
