package main

var Languages = []Entry{
	{
		Name:        "ABC",
		URL:         "homepages.cwi.nl/~steven/abc",
		Date:        "2025-04-04",
		Syntax:      true,
		NoScroll:    true,
		Interactive: false,
	},
	{
		Name:        "Ada",
		URL:         "adaic.org",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Agda",
		URL:         "wiki.portal.chalmers.se/agda",
		Date:        "2025-04-04",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Agora",
		URL:         "soft.vub.ac.be/research/agora",
		Date:        "2025-04-04",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Aldor",
		URL:         "aldor.org",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "ALF",
		URL:         "informatik.uni-kiel.de/~mh/systems/ALF",
		Date:        "2025-04-04",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Alice ML",
		URL:         "ps.uni-saarland.de/alice",
		Date:        "2025-04-04",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "AmbientTalk",
		URL:         "soft.vub.ac.be/amop",
		Date:        "2025-04-04",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "AMPL",
		URL:         "ampl.com/products/ampl",
		Date:        "2025-04-04",
		Syntax:      true,
		NoScroll:    true,
		Interactive: false,
	},
	{
		Name:        "AngelScript",
		URL:         "angelcode.com/angelscript",
		Date:        "2025-04-04",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "APL",
		URL:         "aplwiki.com",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    true,
		Interactive: false,
	},
	{
		Name:        "App Inventor",
		URL:         "appinventor.mit.edu",
		Date:        "2025-04-04",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "AppleScript",
		URL:         "developer.apple.com/library/archive/documentation/AppleScript/Conceptual/AppleScriptLangGuide",
		Date:        "2025-04-04",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "AssemblyScript",
		URL:         "assemblyscript.org",
		Date:        "2025-04-04",
		Syntax:      true,
		NoScroll:    true,
		Interactive: true,
	},
	{
		Name:        "AutoHotKey",
		URL:         "autohotkey.com",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "AutoIt",
		URL:         "autoitscript.com",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Ballerina",
		URL:         "ballerina.io",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Bash",
		URL:         "gnu.org/software/bash",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "BeanShell",
		URL:         "github.com/beanshell/beanshell",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Borgo",
		URL:         "borgo-lang.github.io",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    true,
		Interactive: true,
	},
	{
		Name:        "C",
		URL:         "c-language.org",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "C++",
		URL:         "isocpp.org",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "C#",
		URL:         "learn.microsoft.com/en-us/dotnet/csharp",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Clarion",
		URL:         "softvelocity.com",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Clean",
		URL:         "wiki.clean.cs.ru.nl",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Clojure",
		URL:         "clojure.org",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "CLU",
		URL:         "pmg.csail.mit.edu/CLU.html",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Cobra",
		URL:         "cobra-language.com",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    true,
		Interactive: false,
	},
	{
		Name: "Common Lisp",
		URL:  "common-lisp.net",
		Date: "2025-03-29",
		// Syntax is visible in background image, which is design rather than
		// showcase.
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Crystal",
		URL:         "crystal-lang.org",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    true,
		Interactive: false,
	},
	{
		Name:        "Curry",
		URL:         "curry-lang.org",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    true,
		Interactive: false,
	},
	{
		Name:        "Cython",
		URL:         "cython.org",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "D",
		URL:         "dlang.org",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    true,
		Interactive: true,
	},
	{
		Name:        "Dart",
		URL:         "dart.dev",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    false,
		Interactive: true,
	},
	{
		Name:        "Delphi",
		URL:         "embarcadero.com/products/delphi",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Dylan",
		URL:         "opendylan.org",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Eiffel",
		URL:         "eiffel.org",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    true,
		Interactive: false,
	},
	{
		Name:        "Elixir",
		URL:         "elixir-lang.org",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    true,
		Interactive: false,
	},
	{
		Name:        "Erlang",
		URL:         "erlang.org",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    true,
		Interactive: false,
	},
	{
		Name: "Euphoria",
		URL:  "openeuphoria.org",
		Date: "2025-03-29",
		// Section changes on each visit, and does not always display syntax.
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Factor",
		URL:         "factorcode.org",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    true,
		Interactive: false,
	},
	{
		Name:        "Fennel",
		URL:         "fennel-lang.org",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    true,
		Interactive: true,
	},
	{
		Name:        "Forth",
		URL:         "forth-standard.org",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    true,
		Interactive: false,
	},
	{
		Name:        "Fortran",
		URL:         "fortran-lang.org",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "FreeBasic",
		URL:         "freebasic.net",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    true,
		Interactive: false,
	},
	{
		Name:        "F#",
		URL:         "fsharp.org",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "GLBasic",
		URL:         "glbasic.com",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Gleam",
		URL:         "gleam.run",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    true,
		Interactive: false,
	},
	{
		Name:        "Go",
		URL:         "go.dev",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    false,
		Interactive: true,
	},
	{
		Name:        "Gosu",
		URL:         "gosu-lang.github.io",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Groovy",
		URL:         "groovy-lang.org",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Harbour",
		URL:         "harbour.github.io",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Haskell",
		URL:         "haskell.org",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    true,
		Interactive: false,
	},
	{
		Name:        "Haxe",
		URL:         "haxe.org",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    false,
		Interactive: true,
	},
	{
		Name:        "Io",
		URL:         "iolanguage.org",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "J",
		URL:         "jsoftware.com",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Janet",
		URL:         "janet-lang.org",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    false,
		Interactive: true,
	},
	{
		Name:        "Java",
		URL:         "oracle.com/java",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "JavaScript",
		URL:         "ecma-international.org/publications-and-standards/standards/ecma-262",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "jq",
		URL:         "jqlang.org",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Julia",
		URL:         "julialang.org",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Kotlin",
		URL:         "kotlinlang.org",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    false,
		Interactive: true,
	},
	{
		Name:        "Koto",
		URL:         "koto.dev",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "ksh",
		URL:         "kornshell.com",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Liberty BASIC",
		URL:         "libertybasic.com",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Logtalk",
		URL:         "logtalk.org",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Lua",
		URL:         "lua.org",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Luau",
		URL:         "luau.org",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Module-2",
		URL:         "modula2.org",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Modula-3",
		URL:         "modula3.org",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Nim",
		URL:         "nim-lang.org",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    true,
		Interactive: false,
	},
	{
		Name:        "Oberon",
		URL:         "projectoberon.net",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Objective-C",
		URL:         "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/Introduction/Introduction.html",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "OCaml",
		URL:         "ocaml.org",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    true,
		Interactive: false,
	},
	{
		Name:        "Odin",
		URL:         "odin-lang.org",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    true,
		Interactive: false,
	},
	{
		Name:        "Opa",
		URL:         "opalang.org",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Oxygene",
		URL:         "remobjects.com/elements/oxygene",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Perl",
		URL:         "perl.org",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "PHP",
		URL:         "php.net",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "PowerShell",
		URL:         "microsoft.com/powershell",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "PureBasic",
		URL:         "purebasic.com",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Python",
		URL:         "python.org",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    true,
		Interactive: false,
	},
	{
		Name:        "R",
		URL:         "r-project.org",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Racket",
		URL:         "racket-lang.org",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    true,
		Interactive: false,
	},
	{
		Name:        "Rake",
		URL:         "raku.org",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    true,
		Interactive: false,
	},
	{
		Name:        "Rebol",
		URL:         "rebol.com",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "rhai",
		URL:         "rhai.rs",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Ring",
		URL:         "ring-lang.github.io",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Roc",
		URL:         "roc-lang.org",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    true,
		Interactive: true,
	},
	{
		Name:        "Ruby",
		URL:         "ruby-lang.org",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    true,
		Interactive: false,
	},
	{
		Name:        "Rust",
		URL:         "rust-lang.org",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "S-Lang",
		URL:         "jedsoft.org/slang",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    true,
		Interactive: false,
	},
	{
		Name:        "Scala",
		URL:         "scala-lang.org",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    true,
		Interactive: false,
	},
	{
		Name:        "Scheme",
		URL:         "scheme.org",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Seed7",
		URL:         "seed7.sourceforge.net",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Small Basic",
		URL:         "smallbasic-publicwebsite.azurewebsites.net",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    true,
		Interactive: false,
	},
	{
		Name:        "Snobol",
		URL:         "regressive.org/snobol4",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Solidity",
		URL:         "soliditylang.org",
		Date:        "2026-02-25",
		Syntax:      true,
		NoScroll:    false,
		Interactive: true,
	},
	{
		Name:        "Standard ML",
		URL:         "smlfamily.github.io",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Swift",
		URL:         "swift.org",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    true,
		Interactive: false,
	},
	{
		Name:        "Tcl",
		URL:         "tcl-lang.org",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "TOML",
		URL:         "toml.io",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    true,
		Interactive: false,
	},
	{
		Name:        "V",
		URL:         "vlang.io",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    true,
		Interactive: false,
	},
	{
		Name:        "Visual Basic",
		URL:         "learn.microsoft.com/en-us/previous-versions/visualstudio/visual-basic-6/visual-basic-6.0-documentation",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Visual Basic .NET",
		URL:         "docs.microsoft.com/dotnet/visual-basic",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Visual FoxPro",
		URL:         "msdn.microsoft.com/vfoxpro",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Visual Prolog",
		URL:         "www.visual-prolog.com",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Wolfram Language",
		URL:         "wolfram.com/language",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    false,
		Interactive: true,
	},
	{
		Name:        "Wren",
		URL:         "wren.io",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    true,
		Interactive: false,
	},
	{
		Name:        "XQuery",
		URL:         "w3.org/XML/Query",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Yabasic",
		URL:         "2484.de/yabasic",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    false,
		Interactive: false,
	},
	{
		Name:        "Zig",
		URL:         "ziglang.org",
		Date:        "2025-03-29",
		Syntax:      true,
		NoScroll:    true,
		Interactive: false,
	},
	{
		Name:        "Zsh",
		URL:         "zsh.org",
		Date:        "2025-03-29",
		Syntax:      false,
		NoScroll:    false,
		Interactive: false,
	},
}
