[ada]
name = "Ada"
url = "adaic.org"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[aldor]
name = "Aldor"
url = "aldor.org"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[apl]
name = "APL"
url = "aplwiki.com"
date = 2025-03-29
syntax = true
noscroll = true
interactive = false

[autohotkey]
name = "AutoHotKey"
url = "autohotkey.com"
date = 2025-03-29
syntax = true
noscroll = false
interactive = false

[autoit]
name = "AutoIt"
url = "autoitscript.com"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[ballerina]
name = "Ballerina"
url = "ballerina.io"
date = 2025-03-29
syntax = true
noscroll = false
interactive = false

[bash]
name = "Bash"
url = "gnu.org/software/bash"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[beanshell]
name = "BeanShell"
url = "github.com/beanshell/beanshell"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[borgo]
name = "Borgo"
url = "borgo-lang.github.io"
date = 2025-03-29
syntax = true
noscroll = true
interactive = true

[c]
name = "C"
url = "c-language.org"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[cpp]
name = "C++"
url = "isocpp.org"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[csharp]
name = "C#"
url = "learn.microsoft.com/en-us/dotnet/csharp"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[clarion]
name = "Clarion"
url = "softvelocity.com"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[clean]
name = "Clean"
url = "wiki.clean.cs.ru.nl"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[clojure]
name = "Clojure"
url = "clojure.org"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[clu]
name = "CLU"
url = "pmg.csail.mit.edu/CLU.html"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[cobra]
name = "Cobra"
url = "cobra-language.com"
date = 2025-03-29
syntax = true
noscroll = true
interactive = false

[commonlisp]
name = "Common Lisp"
url = "common-lisp.net"
date = 2025-03-29
# Syntax is visible in background image, which is design rather than showcase.
syntax = false
noscroll = false
interactive = false

[crystal]
name = "Crystal"
url = "crystal-lang.org"
date = 2025-03-29
syntax = true
noscroll = true
interactive = false

[curry]
name = "Curry"
url = "curry-lang.org"
date = 2025-03-29
syntax = true
noscroll = true
interactive = false

[cython]
name = "Cython"
url = "cython.org"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[d]
name = "D"
url = "dlang.org"
date = 2025-03-29
syntax = true
noscroll = true
interactive = true

[dart]
name = "Dart"
url = "dart.dev"
date = 2025-03-29
syntax = true
noscroll = false
interactive = true

[delphi]
name = "Delphi"
url = "embarcadero.com/products/delphi"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[dylan]
name = "Dylan"
url = "opendylan.org"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[eiffel]
name = "Eiffel"
url = "eiffel.org"
date = 2025-03-29
syntax = true
noscroll = true
interactive = false

[elixir]
name = "Elixir"
url = "elixir-lang.org"
date = 2025-03-29
syntax = true
noscroll = true
interactive = false

[erlang]
name = "Erlang"
url = "erlang.org"
date = 2025-03-29
syntax = true
noscroll = true
interactive = false

[euphoria]
name = "Euphoria"
url = "openeuphoria.org"
date = 2025-03-29
# Section changes on each visit, and does not always display syntax.
syntax = false
noscroll = false
interactive = false

[factor]
name = "Factor"
url = "factorcode.org"
date = 2025-03-29
syntax = true
noscroll = true
interactive = false

[fennel]
name = "Fennel"
url = "fennel-lang.org"
date = 2025-03-29
syntax = true
noscroll = true
interactive = true

[forth]
name = "Forth"
url = "forth-standard.org"
date = 2025-03-29
syntax = true
noscroll = true
interactive = false

[fortran]
name = "Fortran"
url = "fortran-lang.org"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[freebasic]
name = "FreeBasic"
url = "freebasic.net"
date = 2025-03-29
syntax = true
noscroll = true
interactive = false

[fsharp]
name = "F#"
url = "fsharp.org"
date = 2025-03-29
syntax = true
noscroll = false
interactive = false

[glbasic]
name = "GLBasic"
url = "glbasic.com"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[gleam]
name = "Gleam"
url = "gleam.run"
date = 2025-03-29
syntax = true
noscroll = true
interactive = false

[go]
name = "Go"
url = "go.dev"
date = 2025-03-29
syntax = true
noscroll = false
interactive = true

[gosu]
name = "Gosu"
url = "gosu-lang.github.io"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[groovy]
name = "Groovy"
url = "groovy-lang.org"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[harbour]
name = "Harbour"
url = "harbour.github.io"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[haskell]
name = "Haskell"
url = "haskell.org"
date = 2025-03-29
syntax = true
noscroll = true
interactive = false

[haxe]
name = "Haxe"
url = "haxe.org"
date = 2025-03-29
syntax = true
noscroll = false
interactive = true

[io]
name = "Io"
url = "iolanguage.org"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[j]
name = "J"
url = "jsoftware.com"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[janet]
name = "Janet"
url = "janet-lang.org"
date = 2025-03-29
syntax = true
noscroll = false
interactive = true

[java]
name = "Java"
url = "oracle.com/java"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[javascript]
name = "JavaScript"
url = "ecma-international.org/publications-and-standards/standards/ecma-262"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[jq]
name = "jq"
url = "jqlang.org"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[julia]
name = "Julia"
url = "julialang.org"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[kotlin]
name = "Kotlin"
url = "kotlinlang.org"
date = 2025-03-29
syntax = true
noscroll = false
interactive = true

[koto]
name = "Koto"
url = "koto.dev"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[ksh]
name = "ksh"
url = "kornshell.com"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[libertybasic]
name = "Liberty BASIC"
url = "libertybasic.com"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[logtalk]
name = "Logtalk"
url = "logtalk.org"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[lua]
name = "Lua"
url = "lua.org"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[luau]
name = "Luau"
url = "luau.org"
date = 2025-03-29
syntax = true
noscroll = false
interactive = false

[modula2]
name = "Module-2"
url = "modula2.org"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[modula3]
name = "Modula-3"
url = "modula3.org"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[nim]
name = "Nim"
url = "nim-lang.org"
date = 2025-03-29
syntax = true
noscroll = true
interactive = false

[oberon]
name = "Oberon"
url = "projectoberon.net"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[objectivec]
name = "Objective-C"
url = "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/Introduction/Introduction.html"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[ocaml]
name = "OCaml"
url = "ocaml.org"
date = 2025-03-29
syntax = true
noscroll = true
interactive = false

[odin]
name = "Odin"
url = "odin-lang.org"
date = 2025-03-29
syntax = true
noscroll = true
interactive = false

[opa]
name = "Opa"
url = "opalang.org"
date = 2025-03-29
syntax = true
noscroll = false
interactive = false

[oxygene]
name = "Oxygene"
url = "remobjects.com/elements/oxygene"
date = 2025-03-29
syntax = true
noscroll = false
interactive = false

[perl]
name = "Perl"
url = "perl.org"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[php]
name = "PHP"
url = "php.net"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[powershell]
name = "PowerShell"
url = "microsoft.com/powershell"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[purebasic]
name = "PureBasic"
url = "purebasic.com"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[python]
name = "Python"
url = "python.org"
date = 2025-03-29
syntax = true
noscroll = true
interactive = false

[r]
name = "R"
url = "r-project.org"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[racket]
name = "Racket"
url = "racket-lang.org"
date = 2025-03-29
syntax = true
noscroll = true
interactive = false

[raku]
name = "Rake"
url = "raku.org"
date = 2025-03-29
syntax = true
noscroll = true
interactive = false

[rebol]
name = "Rebol"
url = "rebol.com"
date = 2025-03-29
syntax = true
noscroll = false
interactive = false

[rhai]
name = "rhai"
url = "rhai.rs"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[ring]
name = "Ring"
url = "ring-lang.github.io"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[roc]
name = "Roc"
url = "roc-lang.org"
date = 2025-03-29
syntax = true
noscroll = true
interactive = true

[ruby]
name = "Ruby"
url = "ruby-lang.org"
date = 2025-03-29
syntax = true
noscroll = true
interactive = false

[rust]
name = "Rust"
url = "rust-lang.org"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[slang]
name = "S-Lang"
url = "jedsoft.org/slang"
date = 2025-03-29
syntax = true
noscroll = true
interactive = false

[scala]
name = "Scala"
url = "scala-lang.org"
date = 2025-03-29
syntax = true
noscroll = true
interactive = false

[scheme]
name = "Scheme"
url = "scheme.org"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[seed7]
name = "Seed7"
url = "seed7.sourceforge.net"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[smallbasic]
name = "Small Basic"
url = "smallbasic-publicwebsite.azurewebsites.net"
date = 2025-03-29
syntax = true
noscroll = true
interactive = false

[snobol]
name = "Snobol"
url = "regressive.org/snobol4"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[sml]
name = "Standard ML"
url = "smlfamily.github.io"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[swift]
name = "Swift"
url = "swift.org"
date = 2025-03-29
syntax = true
noscroll = true
interactive = false

[tcl]
name = "Tcl"
url = "tcl-lang.org"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[toml]
name = "TOML"
url = "toml.io"
date = 2025-03-29
syntax = true
noscroll = true
interactive = false

[v]
name = "V"
url = "vlang.io"
date = 2025-03-29
syntax = true
noscroll = true
interactive = false

[vb]
name = "Visual Basic"
url = "learn.microsoft.com/en-us/previous-versions/visualstudio/visual-basic-6/visual-basic-6.0-documentation"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[vbnet]
name = "Visual Basic .NET"
url = "docs.microsoft.com/dotnet/visual-basic"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[vfoxpro]
name = "Visual FoxPro"
url = "msdn.microsoft.com/vfoxpro"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[visualprolog]
name = "Visual Prolog"
url = "www.visual-prolog.com"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[wolframlanguage]
name = "Wolfram Language"
url = "wolfram.com/language"
date = 2025-03-29
syntax = true
noscroll = false
interactive = true

[wren]
name = "Wren"
url = "wren.io"
date = 2025-03-29
syntax = true
noscroll = true
interactive = false

[xquery]
name = "XQuery"
url = "w3.org/XML/Query"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false

[yabasic]
name = "Yabasic"
url = "2484.de/yabasic"
date = 2025-03-29
syntax = true
noscroll = false
interactive = false

[zig]
name = "Zig"
url = "ziglang.org"
date = 2025-03-29
syntax = true
noscroll = true
interactive = false

[zsh]
name = "Zsh"
url = "zsh.org"
date = 2025-03-29
syntax = false
noscroll = false
interactive = false
